// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_coaches_no_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_no_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_all_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("year", "2015"))
        .and(query_param("firstName", "Nick"))
        .and(query_param("lastName", "Saban"))
        .and(query_param("team", "Alabama"))
        .and(query_param("minYear", "2012"))
        .and(query_param("maxYear", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_all_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
pub async fn mount_coaches_first_name_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("firstName", "nick"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_first_name.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_last_name_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("lastName", "bryant"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_last_name.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("team", "alabama"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("year", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_min_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("minYear", "2018"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_min_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_coaches_max_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/coaches"))
        .and(query_param("maxYear", "1980"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/coaches_max_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
