// @generated by seed_fixtures
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_conference_no_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/conferences"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/conferences_no_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
