// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_drives_required_year_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("year", "2023"))
        .and(query_param("seasonType", "postseason"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_week_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("week", "1"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_week.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("year", "2023"))
        .and(query_param("team", "texas"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_offense_defense_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("offense", "ohio%20state"))
        .and(query_param("defense", "michigan"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_offense_defense.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("year", "2023"))
        .and(query_param("conference", "sec"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_off_conference_def_conference_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("defenseConference", "sec"))
        .and(query_param("offenseConference", "acc"))
        .and(query_param("year", "2025"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_offense_conference_defense_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_drives_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/drives"))
        .and(query_param("classification", "fbs"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/drives_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
