// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_games_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2022"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_required_id_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("id", "401525434"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_required_id.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_week_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_week.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("seasonType", "postseason"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("classification", "fcs"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2023"))
        .and(query_param("team", "LSU"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_home_away_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("home", "alabama"))
        .and(query_param("year", "2023"))
        .and(query_param("away", "lsu"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_home_away.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("conference", "ACC"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("seasonType", "postseason"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_week_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_week.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("year", "2023"))
        .and(query_param("team", "alabama"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("conference", "sec"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_media_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("mediaType", "tv"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_media_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_games_media_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/games"))
        .and(query_param("classification", "fcs"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/games_media_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
