// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_plays_required_year_week_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_required_year_week.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .and(query_param("team", "auburn"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_offense_defense_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("defense", "ohio%20state"))
        .and(query_param("offense", "michigan"))
        .and(query_param("week", "1"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_offense_defense.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_off_conference_def_conference_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("year", "2024"))
        .and(query_param("defenseConference", "sec"))
        .and(query_param("week", "1"))
        .and(query_param("offenseConference", "acc"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_off_conference_def_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("conference", "sec"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_play_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("week", "1"))
        .and(query_param("playType", "RUSH"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_play_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("week", "1"))
        .and(query_param("year", "2023"))
        .and(query_param("seasonType", "postseason"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_plays_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/plays"))
        .and(query_param("year", "2023"))
        .and(query_param("week", "1"))
        .and(query_param("classification", "fcs"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/plays_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
