// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_rankings_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/rankings"))
        .and(query_param("year", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/rankings_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_rankings_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/rankings"))
        .and(query_param("seasonType", "regular"))
        .and(query_param("year", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/rankings_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_rankings_week_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/rankings"))
        .and(query_param("week", "12"))
        .and(query_param("year", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/rankings_week.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
