// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_recruiting_players_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/players"))
        .and(query_param("year", "2022"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_players_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_players_required_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/players"))
        .and(query_param("team", "alabama"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_players_required_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_players_position_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/players"))
        .and(query_param("year", "2022"))
        .and(query_param("position", "qb"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_players_position.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_players_state_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/players"))
        .and(query_param("year", "2022"))
        .and(query_param("state", "al"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_players_state.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_players_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/players"))
        .and(query_param("year", "2022"))
        .and(query_param("classification", "HighSchool"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_players_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_teams_no_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/teams"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_teams_no_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_teams_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/teams"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_teams_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_recruiting_teams_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/recruiting/teams"))
        .and(query_param("team", "clemson"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/recruiting_teams_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
