// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_teams_roster_no_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/roster"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/roster_no_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_teams_roster_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/roster"))
        .and(query_param("team", "florida"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/roster_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_teams_roster_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/roster"))
        .and(query_param("year", "2022"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/roster_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_teams_roster_classification_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/roster"))
        .and(query_param("classification", "fbs"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/roster_classification.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
