// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_stats_player_season_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_player_season_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("conference", "sec"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_player_season_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("team", "alabama"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_player_season_week_range_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("startWeek", "2"))
        .and(query_param("endWeek", "6"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_week_range.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_player_season_season_type_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("year", "2023"))
        .and(query_param("seasonType", "postseason"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_season_type.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_player_season_category_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/player/season"))
        .and(query_param("year", "2023"))
        .and(query_param("category", "passingTDs"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_player_season_category.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_season_required_year_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/season"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_season_required_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_season_required_team_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/season"))
        .and(query_param("team", "alabama"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_season_required_team.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_season_conference_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/season"))
        .and(query_param("conference", "sec"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_season_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_stats_season_week_range_param_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/stats/season"))
        .and(query_param("endWeek", "6"))
        .and(query_param("startWeek", "2"))
        .and(query_param("year", "2023"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/stats_season_week_range.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
