// @generated by seed_fixtures
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

pub async fn mount_teams_no_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/teams"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/teams_no_params.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_teams_conference_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/teams"))
        .and(query_param("conference", "sec"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/teams_conference.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}

pub async fn mount_teams_year_params_stub(server: &MockServer) {
    Mock::given(method("GET"))
        .and(path("/teams"))
        .and(query_param("year", "2024"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            include_str!("../fixtures/teams_year.json"),
            "application/json",
        ))
        .mount(server)
        .await;
}
